//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Samples.ReportingServices.CustomSecurity {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CustomSecurity {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomSecurity() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Samples.ReportingServices.CustomSecurity.CustomSecurity", typeof(CustomSecurity).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 An error occurred while attempting to add the account.  的當地語系化字串。
        /// </summary>
        internal static string AddAccountError {
            get {
                return ResourceManager.GetString("AddAccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Root element is not \&quot;AdminConfiguration\&quot; in config data. 的當地語系化字串。
        /// </summary>
        internal static string AdminConfiguration {
            get {
                return ResourceManager.GetString("AdminConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No Url reservation found for the \&quot;ReportServerWebService\&quot; application. 的當地語系化字串。
        /// </summary>
        internal static string MissingUrlReservation {
            get {
                return ResourceManager.GetString("MissingUrlReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Number of operation names don&apos;t match. 的當地語系化字串。
        /// </summary>
        internal static string OperationNameError {
            get {
                return ResourceManager.GetString("OperationNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 An error occurred while attempting to get the ReportServer Url.  的當地語系化字串。
        /// </summary>
        internal static string RSUrlError {
            get {
                return ResourceManager.GetString("RSUrlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unrecognized configuration element. 的當地語系化字串。
        /// </summary>
        internal static string UnrecognizedElement {
            get {
                return ResourceManager.GetString("UnrecognizedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  user registered 的當地語系化字串。
        /// </summary>
        internal static string UserRegistered {
            get {
                return ResourceManager.GetString("UserRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Exception verifying user.  的當地語系化字串。
        /// </summary>
        internal static string VerifyError {
            get {
                return ResourceManager.GetString("VerifyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 An error occurred while attempting to verify the user. 的當地語系化字串。
        /// </summary>
        internal static string VerifyUserException {
            get {
                return ResourceManager.GetString("VerifyUserException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No WMI class found. 的當地語系化字串。
        /// </summary>
        internal static string WMIClassError {
            get {
                return ResourceManager.GetString("WMIClassError", resourceCulture);
            }
        }
    }
}
